#!/usr/bin/env bash
logpath="/usr/src/paperless/src/scanprep4paperless-ngx/scanprep/s4p.log"
logmsg=$(date +"%D %T")" || scanprep4paperless-ngx (s4p) bash called with file path: '"$1"'"
echo $logmsg>> $logpath
python /usr/src/paperless/src/scanprep4paperless-ngx/scanprep/s4p.py ${1} /usr/src/paperless/consume/
